<?php

define('__BMAP_CONTAINER_ID__', 'BMapContainer');

/**
 * Implements hook_menu().
 */
function bmap_menu() {
  $items = array();
  $items['admin/config/user-interface/bmap'] = array(
    'title' => 'Bmap',
    'description' => 'Bmap settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bmap_settings'),
    'access arguments' => array('administer bmap'),
    'file' => 'bmap.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/structure/bmap'] = array(
    'title' => 'Bmap',
    'description' => 'Manage Bmap',
    'page callback' => 'bmap_manage',
    'access arguments' => array('administer bmap'),
    'file' => 'bmap.admin.inc',
  );
  $items['bmap/add'] = array(
    'title' => 'Add Bmap',
    'page callback' => 'bmap_add',
    'access arguments' => array('administer bmap'),
    'file' => 'bmap.admin.inc',
  );
  $items['admin/structure/bmap/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['bmap/%bmap'] = array(
    'title' => 'Bmap',
    'page callback' => 'bmap_page_view',
    'page arguments' => array(1),
    'access arguments' => array('administer bmap'),
    'file' => 'bmap.admin.inc',
  );
  $items['bmap/%bmap/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['bmap/%bmap/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'bmap_page_edit',
    'page arguments' => array(1),
    'access arguments' => array('administer bmap'),
    'weight' => 0,
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'bmap.admin.inc',
  );
  $items['bmap/%bmap/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('bmap_delete_confirm_form', 1),
    'access arguments' => array('administer bmap'),
    'weight' => 1,
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_INLINE,
    'file' => 'bmap.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function bmap_permission() {
  return array(
    'administer bmap' => array(
      'title' => t('Administer Bmaps'),
      'description' => t('Edit and view all entitiy bmaps.'),
    ),
  );
}

/**
 * Implements hook_entity_info().
 */
function bmap_entity_info() {
  $return = array(
    'bmap' => array(
      'label' => t('Bmap'),
      'plural label' => t('Bmaps'),
      'description' => t('Bmap entity.'),
      'entity class' => 'Bmap',
      'controller class' => 'EntityAPIController',
      'base table' => 'bmap',
      'fieldable' => TRUE,
      'view modes' => array(
        'full' => array(
          'label' => t('Bmap'),
          'custom settings' => FALSE,
        ),
      ),
      'entity keys' => array(
        'id' => 'bid',
      ),
      'bundles' => array(
        'bmap' => array(
          'label' => t('Bmap'),
          'admin' => array(
            'path' => 'admin/structure/bmap',
            'access arguments' => array('administer bmap'),
          ),
        ),
      ),
      'uri callback' => 'entity_class_uri',
      'access callback' => 'bmap_access',
      'module' => 'bmap',
      'metadata controller class' => 'BmapMetadataController'
    ),
  );
  return $return;
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function bmap_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  // Add action link to 'node/add' on 'admin/content' page.
  if ($root_path == 'admin/structure/bmap') {
    $item = menu_get_item('bmap/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}

/**
 * Implements hook_admin_paths().
 */
function bmap_admin_paths() {
  if (variable_get('node_admin_theme')) {
    $paths = array(
      'bmap/add' => TRUE,
      'bmap/*' => TRUE,
      'bmap/*/edit' => TRUE,
      'bmap/*/delete' => TRUE,
    );
    return $paths;
  }
}

/**
 * Implements hook_views_api().
 */
function bmap_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'bmap') . '/views',
  );
}

/**
 * Determines whether the given user has access to a bmap.
 *
 * @param $op
 *   The operation being performed. One of 'view', 'update', 'create', 'delete'
 *   or just 'edit' (being the same as 'create' or 'update').
 * @param $bmap
 *   Optionally to check access for. If nothing is given, access for
 *   all bmaps is determined.
 * @param $account
 *   The user to check for. Leave it to NULL to check for the global user.
 * @return boolean
 *   Whether access is allowed or not.
 */
function bmap_access($op, $bmap = NULL, $account = NULL) {
  if (user_access('administer bmap', $account)) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Fetch a bmap object.
 *
 * @param $bid
 *   Integer specifying the bmap id.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   A fully-loaded $bmap object or FALSE if it cannot be loaded.
 *
 * @see bmap_load_multiple()
 */
function bmap_load($bid, $reset = FALSE) {
  $bmaps = bmap_load_multiple(array($bid), array(), $reset);
  return reset($bmaps);
}

/**
 * Load multiple bmaps based on certain conditions.
 *
 * @param $bids
 *   An array of bmap IDs.
 * @param $conditions
 *   An array of conditions to match against the {bmap} table.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   An array of bmap objects, indexed by pid.
 *
 * @see entity_load()
 * @see bmap_load()
 */
function bmap_load_multiple($bids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('bmap', $bids, $conditions, $reset);
}

/**
 * Deletes a bmap.
 */
function bmap_delete(Bmap $bmap) {
  $bmap->delete();
}

/**
 * Delete multiple bmap.
 *
 * @param $bids
 *   An array of bmap IDs.
 */
function bmap_delete_multiple(array $bids) {
  entity_get_controller('bmap')->delete($bids);
}

/**
 * Create a new bmap object.
 */
function bmap_create(array $values) {
  return new Bmap($values);
}

/**
 * Saves a bmap to the database.
 *
 * @param $bmap
 *   The bmap object.
 */
function bmap_save(Bmap $bmap) {
  return $bmap->save();
}

/**
 * The class used for bamp entities.
 */
class Bmap extends Entity {

  /**
   * The bmap id.
   *
   * @var integer
   */
  public $bid;

  /**
   * The bmap x.
   *
   * @var float
   */
  public $x;

  /**
   * The bmap y.
   *
   * @var float
   */
  public $y;

  public function __construct($values = array()) {
    parent::__construct($values, 'bmap');
  }

  protected function defaultLabel() {
    return $this->path;
  }

  protected function defaultUri() {
    return array('path' => 'bmap/'.$this->bid);
  }  
}

/**
 * The Controller for Bmap entities
 */
class BmapController extends EntityAPIController {
  public function __construct($entityType) {
    parent::__construct($entityType);
  }

  /**
   * Create a bmap - we first set up the values that are specific
   * to our bmap schema but then also go through the EntityAPIController
   * function.
   * 
   * @param $type
   *   The machine-readable type of the bmap.
   *
   * @return
   *   A bmap object with all default fields initialized.
   */
  public function create(array $values = array()) {
    // Add values that are specific to our Bmap
    $values += array(
      'bid' => '',
    );
    
    $bmap = parent::create($values);
    return $bmap;
  }
}